=pod

=head1 NAME

Alien::IUP::Demo -- Demo POD for testing embeded images

=head1 DEMO1 - TABLE

=begin HTML

<p>
<table>
  <tbody>
    <tr>
      <th>Motif</th>
      <td><img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/sample_mot.png" /></td>
    </tr>
    <tr>
      <th>Windows<br>XP Style</th>
      <td><img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/sample_winxp.png" /></td>
    </tr>
  </tbody>
</table>
</p>

=end HTML

=head1 DEMO2 - P1

=begin HTML

<p>MS Windows Classic</p>
<p><img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/sample_win2k.png" alt="Screenshot - Windows Classic" /></p>
<p>GTK</p>
<p><img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/sample_gtk.png" alt="Screenshot - GTK" /></p>

=end HTML

=head1 DEMO3 - P2

=begin HTML

<p>
<img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/iupmenu_gtk.png" alt="Screenshot - Motif" />
<img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.4/pics/iupmenu_mot.png" alt="Screenshot - Windows XP Style" />
</p>

=end HTML

=cut
