=pod

=head1 NAME

Alien::IUP::Demo -- Demo POD for testing embeded images

=head1 DEMO1

=begin HTML

<table cellpadding="1" cellspacing="0" border="1">
  <tbody>
    <tr>
      <th style="background-color:#c0c0c0">Motif</th>
      <td style="background-color:#adb1c2;text-align:center"><img src="sample_mot.png" /></td>
    </tr>
    <tr>
      <th style="background-color:#c0c0c0">Windows<br>Classic</th>
      <td style="background-color:#d4d0c8;text-align:center"><img src="sample_win2k.png" /></td>
    </tr>
    <tr>
      <th style="background-color:#c0c0c0">Windows<br>XP Style</th>
      <td style="background-color:#ece9d8;text-align:center"><img src="pics/sample_winxp.png" /></td>
    </tr>
    <tr>
      <th style="background-color:#c0c0c0">GTK</th>
      <td style="background-color:#efebe7;text-align:center"><img src="/pics/sample_gtk.png" /></td>
    </tr>
  </tbody>
</table>

=end HTML

=head1 DEMO2

=begin HTML

<p><img src="sample_mot.png" alt="Screenshot - Motif" /></p>
<p><img src="pics/sample_winxp.png" alt="Screenshot - Windows XP Style" /></p>
<p><img src="/src/KMX/Alien-IUP-v0.0.3/pics/sample_win2k.png" alt="Screenshot - Windows Classic" /></p>
<p><img src="http://cpansearch.perl.org/src/KMX/Alien-IUP-v0.0.3/pics/sample_gtk.png" alt="Screenshot - GTK" /></p>

=end HTML

=cut
